@startuml StateMachine
hide empty description


[*] --> Idle

Idle --> Run
Run --> Idle

Idle --> NormalAttack
Run --> NormalAttack
NormalAttack --> Idle

Idle --> SpecialAttack
Run --> SpecialAttack
SpecialAttack --> Idle

Idle --> Damage
Run --> Damage
Damage --> Idle

Idle --> FastMove
Run --> FastMove
FastMove --> Idle

Idle --> Warp
Run --> Warp
Warp --> Idle

@enduml